---
title: "Modules"
date: '2022-08-22'
---
## Schedule 

Every morning please come at 9am to complete a Covid antigen test we provide.

| Date | Time|Presenter|Topic|Location|
| ------ | ------ | ------- | ------- | ------- |
| Monday 22 August  | 9a-9:30a |  | Covid protocol and coffee | AHRI seminar rooms 1&2 |
| Monday 22 August  | 9:30a-10:30a | Scott Handley | Workshop Intro and Expectations | AHRI seminar rooms 1&2 |
| Monday 22 August  | 10:30a-12:30p | Lindsay Droit | [Building Successful Sequencing Libraries](modules/building-successful-libraries) | AHRI seminar rooms 1&2 |
| Monday 22 August | 1:30p-4:30p | Scott Handley | [Intro to R and Rstudio](modules/intro-to-r)| AHRI seminar rooms 1&2 |
| ------ | ------ | ------- | ------- | ------- |
| Tuesday 23 August  | 9a-9:30a |  | Covid protocol and coffee | AHRI seminar rooms 1&2 |
| Tuesday 23 August  | 9:30a-12:30p | San Emmaunel James | Intro to the Shell  | AHRI seminar rooms 1&2 |
| Tuesday 23 August | 1:30p-4:30p | San Emmaunel James  | Introduction to Sequencing Data and Quality Control | AHRI seminar rooms 1&2 |
| ------ | ------ | ------- | ------- | ------- |
| Wednesday 24 August  | 9a-9:30a |  | Covid protocol and coffee | AHRI seminar rooms 1&2 |
| Wednesday 24 August  | 9:30a-12:30p | Scott Handley | [Data Visualization and Data Wrangling with the `tidyverse` 1](/modules/data-wrangling-module/) | AHRI seminar rooms 1&2 |
| Wednesday 24 August | 1:30p-4:30p | San Emmaunel James | [Data Visualization and Data Wrangling with the `tidyverse` 2](/modules/data-wrangling-module/) | AHRI seminar rooms 1&2 |
| Wednesday 24 August | 5:30pm-7:30pm | Everyone! | Reception | AHRI seminar rooms 1&2 |
| ------ | ------ | ------- | ------- | ------- |
| Thursday 25 August  | 9a-9:30a |  | Covid protocol and coffee | AHRI seminar rooms 1&2 |
| Thursday 25 August | 9:30a-12:30p | Scott Handley | Explanation of `dada2`, and Processing Raw Amplicon Data in R | AHRI seminar rooms 1&2 |
| Thursday 25 August  | 1:30p-4:30p | Scott Handley | Analyzing and Interpretting Amplicon Data in R | AHRI seminar rooms 1&2 |
| ------ | ------ | ------- | ------- | ------- |
| Friday 26 August  | 9a-9:30a |  | Covid protocol and coffee | AHRI seminar rooms 1&2 |
| Friday 26 August  | 9:30a-12:30p | Fatima Hussain | [Customizations of `ggplot` graphics for publication quality](/modules/figure-customization-module) | AHRI seminar rooms 1&2 |
| Friday 26 August  | 1:30p-4:30p | Everyone | Open Session  | AHRI seminar rooms 1&2 |


------
