languageCode = "en-us"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
buildDrafts = true 
buildFuture = true
baseurl = "https://eda-workshop-durban-2022.org/"
relativeurls = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
theme = "hugo-data-lab"
title = "Durban Exploratory Data Analysis Workshop 2022"
preserveTaxonomyNames = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"

[params]
  copyrightHolder = "Joseph Elsherbini"
  showPoweredBy = true

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Logistics"
  weight = -100 
  identifier = "logistics"
  url = "/logistics/"
[[menu.nav]]
  name = "Modules"
  weight = -90 
  identifier = "modules"
  url = "/modules/"

# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = "Evolution and Genomics site"
  weight = -100 
  identifier = "evomics"
  url = "https://evomics.org/"
[[menu.footer]]
  name = "AHRI"
  weight = -90 
  identifier = "ahri"
  url = "https://www.ahri.org/"
