languageCode = "en-us"
contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"
buildDrafts = true 
buildFuture = true
baseurl = "elsherbini.github.io/AMNH_R_Workshop_2023/"
relativeurls = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
theme = "hugo-data-lab"
title = "NYGC/AMNH Workshop on Microbial Ecology - Introduction to R "
preserveTaxonomyNames = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Modules"
  weight = -100 
  identifier = "modules"
  url = "/modules/"
[[menu.nav]]
  name = "R Glossary"
  weight = -90 
  identifier = "glossary"
  url = "/glossary/"

# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = "Evolution and Genomics site"
  weight = -100 
  identifier = "evomics"
  url = "https://evomics.org/"
[[menu.footer]]
  name = "NYGC"
  weight = -90 
  identifier = "nygc"
  url = "https://www.nygenome.org/"
[[menu.footer]]
  name = "AMNH"
  weight = -80 
  identifier = "amnh"
  url = "https://www.amnh.org/"
