---
title: "Home"
date: '2022-07-18'
---

## 2022 Durban Workshop on Exploratory Data Analysis and Modelling in R

A workshop exploring data analysis and modelling 
techniques in R with a special emphasis on microbiome applications. This 
exciting workshop will run August 22-26, 2022 at the Nelson Mandela School 
of Medicine, University of KwaZulu Natal, in Durban, SA.


## Schedule 

| Date | Day |Time|Presenter|Topic|Location|
| ------ | ------ | ------ | ------- | ------- | ------- |
| 22 August | Monday | AM | Lindsay Droit | [Wet Lab Considerations for Microbiome Data Generation](/modules/microbiome-wet-lab/) | AHRI Seminar Rooms 1&2 |
| 22 August | Monday | PM | 22 August | Scott Handley | Intro to R and Rstudio  | AHRI Seminar Rooms 1&2 |
| 23 August | Tuesday | AM | San Emmaunel James | Processing Raw Amplicon Sequencing Data with Terra.bio  | AHRI Seminar Rooms 1&2 |
| 23 August | Tuesday | PM | San Emmaunel James  | Introduction to Sequencing Data and Quality Control | AHRI Seminar Rooms 1&2 |
| 24 August | Wednesday | AM | Joseph Elsherbini | Exploratory Data Analysis of Tabular Data in R   | AHRI Seminar Rooms 1&2 |
| 24 August | Wednesday | PM | Joseph Elsherbini | Data Visualization in R using the tidyverse   | AHRI Seminar Rooms 1&2 |
| 24 August | Thursday | AM | Scott Handley |  	Preprocessing Microbiome Data for Quantitative Microbiome Analysis  | AHRI Seminar Rooms 1&2 |
| 24 August | Thursday | PM | Scott Handley| Processing Microbiome Data for Quantitative Microbiome Analysis  | AHRI Seminar Rooms 1&2 |
| 25 August | Friday | AM | Joseph Elsherbini | Customizations of `ggplot` graphics for publication quality    | AHRI Seminar Rooms 1&2 |
| 25 August | Friday | PM | Everyone | Open Session  | AHRI Seminar Rooms 1&2 |