---
title: "Logistics"
date: '2022-08-22'
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

## Location
The workshop (Aug. 22-26) will be held at the [Nelson Mandela School of Medicine, University of KwaZulu-Natal](https://www.google.com/maps/place/719+Umbilo+Rd,+Glenwood,+Durban,+4001,+South+Africa/@-29.8775513,30.9857393,15.28z/data=!4m5!3m4!1s0x1ef7a98881a87601:0xaf44019c640d0d69!8m2!3d-29.87845!4d30.990724?shorturl=1):

> AHRI Seminar Rooms 1&2,    
> Nelson R Mandela School of Medicine  
> 719 Umbilo Road, Durban, South Africa  

Breakfast, lunch, and tea break will be provided during the workshop. There will be a reception in the seminar rooms on Wednesday after the course concludes for the day with light food options provided to all participants. The course **runs 9am-4:30pm daily, with sessions from 9:30-12:30 and 1:30-4:30.**

## Laptop requirements

Participants in the Workshop are expected to bring their own computer and charger. Please ensure that this is a modern laptop with a 64-bit operating system (Windows 7 or higher, Mac OS X, etc.). Anything purchased within the last 3-4 years is likely to be fine. It is crucial that you are comfortable working for several hours at time on this machine so please do not bring netbooks with small keyboards or screens. Ensure that the wireless system (wifi) is working prior to the course.
You will need to run the workshop software on **an up-to-date version of [Mozilla Firefox](https://www.mozilla.org/en-US/firefox/new/) or [Google Chrome](https://www.google.com/chrome/).** Please make sure you have the latest version of your preferred web browser installed.

## Registering for Terra

At the beginning of the Workshop, everyone accesses the Terra.bio software that will be used throughout the course. This software will be accessed as a cloud instance. The cloud will contain all necessary example files required to complete the Workshop.
There are two steps to prepare your Terra account for the workshop. Try your best to register before Monday, 8/22. We will assist should you become stuck.  

1. **Please register for a Terra account using the link and instructions found [here](https://support.terra.bio/hc/en-us/articles/360028235911).**  
2. **[Please submit your Terra account email on this form](https://forms.gle/anEvCVCaCLZsV1GS6) so we can manually add you to our Terra cloud for the workshop.**  

## Joining the message board

Please join the discord here: https://discord.gg/hPyzrKJy

## Schedule 

Every morning please come at 9am to complete a Covid antigen test we provide.

## Schedule 

Every morning please come at 9am to complete a Covid antigen test we provide.

| Date | Time|Presenter|Topic|Location|
| ------ | ------ | ------- | ------- | ------- |
| Monday 22 August  | 9a-9:30a |  | Covid protocol and coffee | AHRI seminar rooms 1&2 |
| Monday 22 August  | 9:30a-10:30a | Scott Handley | [Workshop Intro, Expectations,  and Terra Access](/modules/intro-terra-access) | AHRI seminar rooms 1&2 |
| Monday 22 August  | 10:30a-12:30p | Lindsay Droit | [Building Successful Sequencing Libraries](/modules/building-successful-libraries) | AHRI seminar rooms 1&2 |
| Monday 22 August | 1:30p-4:30p | Scott Handley | [Intro to R and Rstudio](/modules/intro-to-r)| AHRI seminar rooms 1&2 |
| ------ | ------ | ------- | ------- | ------- |
| Tuesday 23 August  | 9a-9:30a |  | Covid protocol and coffee | AHRI seminar rooms 1&2 |
| Tuesday 23 August  | 9:30a-12:30p | San Emmaunel James | [Intro to the Shell](/modules/intro-unix)  | AHRI seminar rooms 1&2 |
| Tuesday 23 August | 1:30p-4:30p | San Emmaunel James  | [Introduction to Sequencing Data and Quality Control](/modules/intro-bioinformatics) | AHRI seminar rooms 1&2 |
| ------ | ------ | ------- | ------- | ------- |
| Wednesday 24 August  | 9a-9:30a |  | Covid protocol and coffee | AHRI seminar rooms 1&2 |
| Wednesday 24 August  | 9:30a-12:30p | Scott Handley | [Data Visualization and Data Wrangling with the `tidyverse` 1](/modules/data-wrangling-module/) | AHRI seminar rooms 1&2 |
| Wednesday 24 August | 1:30p-4:30p | San Emmaunel James | [Data Visualization and Data Wrangling with the `tidyverse` 2](/modules/data-wrangling-module/) | AHRI seminar rooms 1&2 |
| Wednesday 24 August | 5:30pm-7:30pm | Everyone! | Reception | AHRI seminar rooms 1&2 |
| ------ | ------ | ------- | ------- | ------- |
| Thursday 25 August  | 9a-9:30a |  | Covid protocol and coffee | AHRI seminar rooms 1&2 |
| Thursday 25 August | 9:30a-12:30p | Scott Handley | Explanation of `dada2`, and Processing Raw Amplicon Data in R | AHRI seminar rooms 1&2 |
| Thursday 25 August  | 1:30p-4:30p | Scott Handley | Analyzing and Interpretting Amplicon Data in R | AHRI seminar rooms 1&2 |
| ------ | ------ | ------- | ------- | ------- |
| Friday 26 August  | 9a-9:30a |  | Covid protocol and coffee | AHRI seminar rooms 1&2 |
| Friday 26 August  | 9:30a-12:30p | Fatima Hussain | [Customizations of `ggplot` graphics for publication quality](/modules/figure-customization-module) | AHRI seminar rooms 1&2 |
| Friday 26 August  | 1:30p-4:30p | Everyone | Open Session  [terra wind down slides](Terra_Wind_down.pdf) | AHRI seminar rooms 1&2 |


